/machine_executor_node:
  ros__parameters:
    autostart: false
    blackboard:
      persistent: false
    dua:
      tf_server:
        get_transform: true
        transform_pose: true
        wait_servers: false
    timeout_sec: 5.0
    transitions:
      initial_state: ''
      routines_module: ''
      states:
        - ''
      transitions_table:
        - ''
    use_sim_time: false
    wait_servers: false
